---
service_name: "mssql"
service_instance: "{{ service_name }}-{{ _apb_service_instance_id }}"
service_port: 1433
state: "present"

mssql_eula: "{{ ACCEPT_EULA | default('false') }}"

mssql_image: "docker.io/tchughesiv/mssql-server-linux"
mssql_image_tag: "{{ MSSQL_IMAGE_TAG | default('latest') }}"
mssql_image_pull: "{{ MSSQL_IMAGE_PULL | default('IfNotPresent') }}"
mssql_local: "{{ MSSQL_LOCAL_IS | default('false') }}"

mssql_pid: "{{ MSSQL_PID | default('Developer') }}"
mssql_lcid: "{{ MSSQL_LCID | default('1033') }}"
mssql_agent: "{{ MSSQL_AGENT_ENABLED | default('false') }}"

mssql_data_volume_name: "{{ service_name }}-data"
mssql_data_path: "/var/opt/mssql/data"

mssql_db: "{{ MSSQL_DATABASE | default('TestDB') }}"
mssql_sa_pw: "{{ MSSQL_PASSWORD | default('Hello123!') }}"

volume_size: "{{ MSSQL_DATA_STORAGE_SIZE | default('1') }}"
memory_limit: "{{ MSSQL_MEMORY_LIMIT | default('3') }}"
memory_request: "{{ MSSQL_MEMORY_REQUEST | default('2') }}"
